# https://github.com/labstack/echo/blob/master/middleware/cors.go#L16
allow_credentials: true
allow_origins:
  - http://localhost:5173
  - aevteam.com
allow_methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
allow_headers:
  - Origin
  - Content-Type
  - Authorization
expose-headers:
  - Content-Range
  - X-Content-Range
max-age: 3600
